"""Initial migration

Revision ID: 6f284b403cad
Revises: b711ed733271
Create Date: 2025-03-10 19:46:39.714666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f284b403cad'
down_revision: Union[str, None] = 'b711ed733271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post_audios', ['post_id'])
    op.create_unique_constraint(None, 'post_videos', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_videos', type_='unique')
    op.drop_constraint(None, 'post_audios', type_='unique')
    # ### end Alembic commands ###
