"""update location and user event payment relation table

Revision ID: 7a5d342d9390
Revises: 7e9d1b87976f
Create Date: 2025-03-10 20:06:27.014993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5d342d9390'
down_revision: Union[str, None] = '7e9d1b87976f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
