"""update location and user birthdate can be null table

Revision ID: aa072bb14c6c
Revises: b6f401b4c669
Create Date: 2025-03-11 00:07:32.068722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa072bb14c6c'
down_revision: Union[str, None] = 'b6f401b4c669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
