"""update location and user event payment relation table

Revision ID: b0acfaacee6a
Revises: 7a5d342d9390
Create Date: 2025-03-10 20:14:47.111003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0acfaacee6a'
down_revision: Union[str, None] = '7a5d342d9390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
